module.exports = [
    // 'x264-caffeine', 
    // '1080p',  
    // 'webrip',
    // '720p', 
    // 'tgx',
    // 'h264-cakes',
    // 'web',
    // 'ddp5',
    // '[rartv]',
    // 'mvk',
    // '265-sigma',
    // 'amzn',
    // 'web-dl',
    // 'x264', 
    /x\d*/g,
    /h26\d\.*/g,
    /26\d\.*/g,
    /\d*mb/g,
    /\d{3,4}p/g,
    /yts*/g,
    /\bweb*/g,
    /tgx/g,
    /lt/g,
    /mp4/g,
    /mvk/g,
    /amzn/g,
    /ddp5/g,
    /rartv/g,
    /\s5\s1/g
    
    //
    // '650mb', 
    // 'nitro', 
    // '-xpoz',
    // 'yts',
    // 'mx',
    // 'lt',
    // 'x264-',
    // 'mp4',
    // 'mkv'
]