module.exports = [
    /\bx\d*/g,
    /\bh26\d\.*/g,
    /\b26\d\.*/g,
    /\b\d*mb/g,
    /\b\d{3,4}p/g,
    /\byts*/g,
    /\bweb*/g,
    /\btgx\b/g,
    /\blt\b/g,
    /\bmp4\b/g,
    /\bmvk\b/g,
    /\bamzn\b/g,
    /\bddp5\b/g,
    /\brartv\b/g,
]